sudo: required
services:
  - docker
install:
  - docker build -t test-integration-nodejs:latest .
  - >
    docker run
    -e "CIRCLE_PROJECT_REPONAME=$(echo $TRAVIS_REPO_SLUG | cut -f2 -d '/')"
    -e "CIRCLE_BUILD_NUM=${TRAVIS_BUILD_NUMBER}"
    -e "IMAGE=${IMAGE:-coreos-beta}"
    -e "CHANNEL=${CHANNEL:-development}"
    -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"                                                                                                                                                                                                    
    -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"                                                                                                                                                                                            
    --name=test-integration-nodejs-init test-integration-nodejs:latest /initialize.sh
  - docker commit test-integration-nodejs-init test-integration-nodejs:latest
script:
  - docker run --name=test-integration-nodejs-hello-world test-integration-nodejs:latest /run_hello_world_test.sh
  - docker run --name=test-integration-nodejs-apt-packages test-integration-nodejs:latest /run_apt_packages_test.sh
  - docker run --name=test-integration-nodejs-restart test-integration-nodejs:latest /run_restart_test.sh
after_script:
  - docker run --name=DUMP-test-integration-nodejs test-integration-nodejs:latest vagrant ssh -- sudo journalctl
  - docker run --name=DESTROY-test-integration-nodejs test-integration-nodejs:latest vagrant destroy -f

