FROM experimentalplatform/test-integration-baseimage:latest

ADD run_hello_world_test.sh /run_hello_world_test.sh
ADD run_apt_packages_test.sh /run_apt_packages_test.sh
ADD run_restart_test.sh /run_restart_test.sh
RUN chmod 755 /run_hello_world_test.sh /run_apt_packages_test.sh /run_restart_test.sh

RUN mkdir -p /.ssh && ssh-keygen -C "autogenerated $(date)" -V "+2h" -N "" -f /.ssh/id_rsa
RUN cp -a /.ssh /root/

CMD [ "/bin/bash" ]